In [2]:
import numpy as np

### Consider the below code to answer further questions:
import numpy as np<br>
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]<br>
array_list = np.array(object = list_)<br>
### Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.
### Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.

In [4]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)
print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


In [5]:
for i in array_list:
    print(f"{i}: {type(i)}")

1: <class 'numpy.str_'>
2: <class 'numpy.str_'>
3: <class 'numpy.str_'>
4: <class 'numpy.str_'>
5: <class 'numpy.str_'>


In [6]:
[f"{i}: {type(i)}" for i in list_]

["1: <class 'str'>",
 "2: <class 'str'>",
 "3: <class 'str'>",
 "4: <class 'str'>",
 "5: <class 'str'>"]

### Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
### Will there be any difference in the data type of the elements present in both the variables, list_ and array_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list.

In [7]:
array_list = np.array(object = list_, dtype = int)
print([f"{i}: {type(i)}" for i in list_])
print([f"{i}: {type(i)}" for i in array_list])
#So aray_list dataype changes from a numpy string to a integer

["1: <class 'str'>", "2: <class 'str'>", "3: <class 'str'>", "4: <class 'str'>", "5: <class 'str'>"]
["1: <class 'numpy.int32'>", "2: <class 'numpy.int32'>", "3: <class 'numpy.int32'>", "4: <class 'numpy.int32'>", "5: <class 'numpy.int32'>"]


In [9]:
array_list.dtype

dtype('int32')

### Consider the below code to answer further questions:
import numpy as np<br>
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]<br>
num_array = np.array(object = num_list)<br>
### Q4. Write a code to find the following characteristics of variable, num_array:
- (i) shape
- (ii) size

In [10]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [11]:
num_array.shape

(2, 3)

In [12]:
num_array.size

6

### Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [14]:
zeros_arr = np.zeros((3,3))
print(zeros_arr)
print(f"size: {zeros_arr.size} and shape: {zeros_arr.shape}")

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
size: 9 and shape: (3, 3)


### Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [17]:
idenetity_arr = np.eye(5)
print(idenetity_arr)
print(f"size: {idenetity_arr.size} and shape: {idenetity_arr.shape}")

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
size: 25 and shape: (5, 5)
