In [1]:
import numpy as np

## Rotating Array

In [3]:
arr = np.random.randint(1,10,(4,4))
print(f"orignal:\n{arr}")
print(f"Rotated array:\n{arr.T}")

orignal:
[[1 9 5 9]
 [4 7 5 1]
 [1 5 8 6]
 [1 7 7 2]]
Rotated array:
[[1 4 1 1]
 [9 7 5 7]
 [5 5 8 7]
 [9 1 6 2]]


## Flatten Array
converts any array 2 1d array

In [7]:
arr.flatten()

array([1, 9, 5, 9, 4, 7, 5, 1, 1, 5, 8, 6, 1, 7, 7, 2])

In [8]:
arr.flatten().shape

(16,)

In [9]:
arr.flatten().ndim

1

## Expand and Squeeze Dimension

#### np.expand_dims()
expands dimension by 1

In [15]:
#row wise dimwnsion expansion
expand_row = np.expand_dims(arr,axis=0)
print(expand_row)
print(expand_row.ndim)

[[[1 9 5 9]
  [4 7 5 1]
  [1 5 8 6]
  [1 7 7 2]]]
3


In [23]:
#column wise dimension expansion
expand_col = np.expand_dims(arr,axis=1)
print(expand_col)
print(expand_col.ndim)

[[[1 9 5 9]]

 [[4 7 5 1]]

 [[1 5 8 6]]

 [[1 7 7 2]]]
3


#### np.squeeze()
squeezes dimension by 1

In [21]:
data = np.array([[1],[2],[3]])
print(data.ndim)
print(data.shape)
data = np.squeeze(data)
print(data)
print(data.ndim)

2
(3, 1)
[1 2 3]
1


#### np.repeat(data, repeat no)

In [24]:
np.repeat(data,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

### Rolling Dataset

In [28]:
drr = np.random.randint(1,100,(3,4))
drr

array([[68, 46, 90, 65],
       [ 6,  7, 62, 13],
       [54, 75, 75, 67]])

In [36]:
np.roll(drr,2)

array([[75, 67, 68, 46],
       [90, 65,  6,  7],
       [62, 13, 54, 75]])

In [34]:
np.roll(drr,2,axis=1)

array([[90, 65, 68, 46],
       [62, 13,  6,  7],
       [75, 67, 54, 75]])

In [35]:
np.roll(drr,2,axis=0)

array([[ 6,  7, 62, 13],
       [54, 75, 75, 67],
       [68, 46, 90, 65]])

### Creating Diagonal matrix from a flattened array

In [40]:
np.diag(arr.flatten())

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 6, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2]])

## Numpy Binary Operation
- arr1+arr2
- arr1-arr2
- arr1/arr2
- arr1*arr2
- arr1>arr2
- arr1<arr2
- arr1**arr2
- ~arr1: negation of arr converts all the elements to -ve nos.

## 'Numpy String Operation

In [44]:
arr = np.array(['asit','shastr'])
arr

array(['asit', 'shastr'], dtype='<U6')

**app.char.upper()**

In [45]:
np.char.upper(arr)

array(['ASIT', 'SHASTR'], dtype='<U6')

**Capitalize**

In [46]:
np.char.capitalize(arr)

array(['Asit', 'Shastr'], dtype='<U6')

**Title**

In [47]:
np.char.title(arr)

array(['Asit', 'Shastr'], dtype='<U6')

**All string mehtods are available inside the no.char**

## Numpy Sinosodial Functions

In [51]:
arr1 = np.random.randint(10,90,(3,4))
arr1

array([[22, 11, 71, 57],
       [13, 27, 35, 88],
       [76, 40, 12, 87]])

In [52]:
np.sin(arr1)

array([[-0.00885131, -0.99999021,  0.95105465,  0.43616476],
       [ 0.42016704,  0.95637593, -0.42818267,  0.0353983 ],
       [ 0.56610764,  0.74511316, -0.53657292, -0.82181784]])

In [53]:
np.cos(arr1)

array([[-0.99996083,  0.0044257 , -0.30902273,  0.89986683],
       [ 0.90744678, -0.29213881, -0.90369221,  0.99937328],
       [ 0.82433133, -0.66693806,  0.84385396,  0.56975033]])

In [54]:
np.tan(arr1)

array([[ 8.85165604e-03, -2.25950846e+02, -3.07762040e+00,
         4.84699227e-01],
       [ 4.63021133e-01, -3.27370380e+00,  4.73814720e-01,
         3.54205013e-02],
       [ 6.86747689e-01, -1.11721493e+00, -6.35859929e-01,
        -1.44241747e+00]])

- np.sqrt()
- np.mean()
- np.median()
- np.std()
- np.var()
- np.min()
- np.max()
<br>

- np.add()
- np.subtract()
- np.multiply()
- np.mod()
- np.power()
- np.sqrt()

In [56]:
np.power(arr1,2)

array([[ 484,  121, 5041, 3249],
       [ 169,  729, 1225, 7744],
       [5776, 1600,  144, 7569]], dtype=int32)