In [43]:
import numpy as np

#### Converting a list into an array using numpy

In [9]:
l=[i for i in range(1,11)]
arr= np.array(l)
print(arr)
print(type(arr))
print(len(arr))

[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>
10


In [13]:
#Or array can also be created using 
np.asarray(l)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Creating a array for nested array (2D-Array)

In [16]:
l1=[[1,2,3,4,5],[6,7,8,9,10]]
arr1 = np.array(l1)
print(arr1)
#prints an n 2 dimentional array

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


**array.ndim**- used to calculate the dimension of a array

In [17]:
arr.ndim # 1-dimensional array

1

In [19]:
arr1.ndim # 2-dimensional array

2

### Matrices
##### use: array.matrix(l) to convert to a matrix
##### A matrix is by default a 2d array

In [20]:
#converting l into a matrix
mat = np.matrix(l)
print(mat)


[[ 1  2  3  4  5  6  7  8  9 10]]


observe that that the np.matrix add 2 brackets because by default a matrix is a 2d array

**Q- Converting above given matrix a san array**

In [21]:
np.asanyarray(mat)

matrix([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

**Observation**: Matrix can not be conver to an array because np.asanyarray converts a data into an array and matrix being a 2-dimentional array i.e a subclass of array it can't be cinverted to an array again

## Deep Copy vs Swallow Copy

### Swallow Copy

In [23]:
a = arr
arr[0]=100
print(arr)
print(a)

[100   2   3   4   5   6   7   8   9  10]
[100   2   3   4   5   6   7   8   9  10]


**Observation:** as the value of a[0] is changed the value of a[0] is also changed
#### Reason: Variable arr is just a reference that is pointing towards a memory location and command a=arr creates another reference veriable 'a' that is point to that memory location. So any change in either will be reflected on both

### Deep Copy

In [24]:
b = np.copy(arr)
arr[0]=200
print(arr)
print(b)

[200   2   3   4   5   6   7   8   9  10]
[100   2   3   4   5   6   7   8   9  10]


#### Reason: <u> np.copy()</u> Method creates a new memory location for the data and b will be pointing toward the new location different from arr

## np.fromfunction()
takes a function and creates an arrray based on that function

In [26]:
np.fromfunction(lambda i,j:i==j , (3,3) )
#here if condition i==j is true then true is printed
#(3,3)- signifies a 2=d matrix

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [27]:
np.fromfunction(lambda i,j:i*j , (3,3) )

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

## Creating array from Iterable Object

In [33]:
iterable_obj = (i*i for i in range(10))
print(type(iterable_obj))

#creating array using np.array 
# np.array(iterable_obj)  #o/p- array(<generator object <genexpr> at 0x0000023456E8BAC0>, dtype=object)

#np.fromiter()
np.fromiter(iterable_obj,float)

<class 'generator'>


array([ 0.,  1.,  4.,  9., 16., 25., 36., 49., 64., 81.])

## Creating array from a string

In [37]:
np.fromstring('2023-03-03',int,sep='-')

array([2023,    3,    3])

## Functions to View info. about an Array

### .ndim

In [38]:
arr1.ndim

2

### .size
Tells total no of elements inside an array

In [40]:
arr1.size

10

### .shape

In [41]:
arr1.shape

(2, 5)

### .dtype

In [42]:
arr1.dtype

dtype('int32')